### ISSUE TITLE
.Net Maui Support ? 

### ISSUE THREAD

**Issue by samirgcofficial** [yushulx/Xamarin-forms-document-scanner#2]
Is document scanner available for maui ?

**Comment by yushulx** [comment]
@samirgcofficial not yet. I'll let you know when it's ready.

**Comment by yushulx** [comment]
@samirgcofficial Please try [https://github.com/yushulx/maui-barcode-qrcode-scanner](https://github.com/yushulx/maui-barcode-qrcode-scanner) for .NET MAUI. I'll close the Xamarin repo soon.
